
stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: SecurityAnalysis
        displayName: Security Analysis
        workspace:
          clean: all
        steps:
          - task: SOOS.SOOS-Security-Analysis.scan-task.SOOS@0
            displayName: 'Start Dev Analysis'
            continueOnError: true
            inputs:
              apiKey: ZTU1ZDY1MGMtZjM0YS00NDFjLWJhMDMtMjIxM2NhNDhlYjRl
              path: $(Build.SourcesDirectory)
              clientId: d7dfb7ca7b58f9bf96c11e8b9c881d6eaa0a99dd5bbb9565cb0254ef12f5012f
              project: "Frankenstein"
              baseUri: 'https://dev-api.soos.io/api/'
              
