on: 
  push:
    branches:
      - main
name: generate-sums
jobs:
  generate-sums:
    runs-on: ubuntu-latest 
    steps:
      - uses: tristan-weil/ghaction-checksum-sign-artifact@v1.0.1
        with:
          path: "./*.txt"
          checksum_digests: sha256
          checksum_format: gnu 
          checksum_output: one_file_per_digest
