on: 
  push:
    branches:
      - main


name: generate-sums
jobs:
  generate-sums:
    runs-on: ubuntu-latest
     - name: 'Create a file'
       run: echo "I won't live long" > my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v2
       with:
        name: my_checksum
        path: my_requirements.sha256
        retention-days: 5
