on: 
  push:
    branches:
      - main


name: generate-sums
jobs:
  generate-sums:
    runs-on: ubuntu-latest 
    steps:
#       - name: Checkout 
#         uses: actions/checkout/@v1.0.0
#       - uses: dorny/paths-filter@v2.2.1
#         id: filter 
#         with:
#           filters: | 
#             txt:
#             - '**/*.txt'
            
      - name: Create Digests
        if: ${{ steps.filter.outputs.txt == 'true' }}
        run:
          shasum -a 256 some_requirements.txt>some_requirements.sha256
      - name: Do git stuff 
        run:
          git add .

          git remote add origin
          git push --set-upstream origin main
