on: 
  push:
    branches:
      - main


name: generate-sums
jobs:
  generate-sums:
    runs-on: ubuntu-latest 
    steps:
      - uses: action/checkout@v2
      - name: Check for Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
      - name: Create Checksum file 
      id: checksum-digest
      if: steps.changes.outputs.backend == 'true'
      run:
        shasum -a 256 some_requirements.txt > some_requirements.sha256
      
