on: 
  push:
    branches:
      - main


name: generate-sums
jobs:
  generate-sums:
    runs-on: ubuntu-latest
    steps:
      - run: |
          shasum -a 256 some_requirements.txt>some_requirements.sha256
      - uses: actions/upload-artifact@v2
        with:
          name: my_checksum
          path: some_requirements.sha256
          retention-days: 5
